name: workflow.yml
on:
  pull_request:
    branches:
      - main
jobs:
  build:
    name: Build & Test
    runs-on: ubuntu-latest
    permissions:
      checks: write
      contents: read #This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Set up Java version
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'microsoft'

      - name: Build with Maven
        run: mvn clean install -DskipTests

      - name: Run Tests
        run: mvn test

      - name: Publish Test Report
        if: success() || failure()
        uses: scacap/action-surefire-report@v1